import Link from "next/link";
import { ArrowRight, Play, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";

export function HeroSection() {
  return (
    <section className="relative min-h-screen flex items-center justify-center pt-24 pb-16 px-4 sm:px-6 lg:px-8">
      <div className="mx-auto max-w-5xl text-center">
        <div className="animate-fade-in-up">
          <Badge variant="neon" className="mb-6 px-4 py-1.5">
            <Sparkles className="h-3 w-3 mr-1.5 inline" />
            AI-Powered Reel Studio
          </Badge>
        </div>
        <h1
          className="animate-fade-in-up text-4xl sm:text-5xl md:text-6xl lg:text-7xl font-bold tracking-tight leading-[1.1] mb-6"
          style={{ animationDelay: "80ms" }}
        >
          Create viral reels{" "}
          <span className="neon-text">in seconds</span>
        </h1>
        <p
          className="animate-fade-in-up text-lg sm:text-xl text-muted-foreground max-w-2xl mx-auto mb-10"
          style={{ animationDelay: "160ms" }}
        >
          Hooks, scripts, scene breakdowns, captions, hashtags, and production
          notes — generated by AI for Instagram, TikTok, YouTube & LinkedIn.
        </p>
        <div
          className="animate-fade-in-up flex flex-col sm:flex-row items-center justify-center gap-4"
          style={{ animationDelay: "240ms" }}
        >
          <Button variant="neon" size="lg" asChild>
            <Link href="/signup" prefetch>
              Start Creating Free
              <ArrowRight className="h-5 w-5" />
            </Link>
          </Button>
          <Button variant="glass" size="lg" asChild>
            <a href="#demo">
              <Play className="h-5 w-5" />
              Watch Demo
            </a>
          </Button>
        </div>
        <div
          className="animate-fade-in-up mt-16 relative"
          style={{ animationDelay: "320ms" }}
        >
          <div className="glass rounded-2xl p-1 max-w-3xl mx-auto md:neon-glow">
            <div className="rounded-xl bg-zinc-950/80 p-6 sm:p-8 text-left">
              <div className="flex items-center gap-2 mb-4">
                <div className="h-3 w-3 rounded-full bg-red-500/80" />
                <div className="h-3 w-3 rounded-full bg-yellow-500/80" />
                <div className="h-3 w-3 rounded-full bg-green-500/80" />
                <span className="ml-2 text-xs text-muted-foreground">
                  reel-forge.ai/generate
                </span>
              </div>
              <p className="text-violet-300 text-sm font-mono mb-2">
                {"// Generated hook"}
              </p>
              <p className="text-lg sm:text-xl font-semibold text-white mb-4">
                &quot;Stop scrolling — this one mistake costs creators 10K views
                per reel.&quot;
              </p>
              <p className="text-muted-foreground text-sm">
                + Full script · 5 scenes · 18 hashtags · B-roll ideas
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
